get http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjk5NzQwNjAzLCJleHAiOjE2OTk3NDA2MTh9.CtiU9J8R-eABq5lEqo_IAcSFLBbIJPgcAhBgi3-E5qY

### 

post http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjk5NzQwOTgzfQ._WxXKXHRfYzr0Zn42-K9EWf3blA5wE4L_GU1QUOUoqo"
}

###

post http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}


###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjk5NzQwOTgzfQ._WxXKXHRfYzr0Zn42-K9EWf3blA5wE4L_GU1QUOUoqo"
}